//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tren3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class TrenEntities : DbContext
    {
        private static TrenEntities _context = new TrenEntities();
        public TrenEntities()
            : base("name=TrenEntities")
        {
        }
        public static TrenEntities GetContext()
        {
            if (_context == null)
                _context = new TrenEntities();
            return _context;

        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Sklad> Sklad { get; set; }
        public virtual DbSet<StroyMaterial> StroyMaterial { get; set; }
    }
}
