//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tren3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
<<<<<<< Updated upstream:Model1.Context.cs
    public partial class DbEntities : DbContext
    {
        public DbEntities()
            : base("name=DbEntities")
        {
        }
    
=======
    public partial class Tren3Entities1 : DbContext
    {
        private static Tren3Entities1 _context;
        public Tren3Entities1()
            : base("name=Tren3Entities1")
        {
        }
        public static Tren3Entities1 GetContext()
        {
            if (_context == null)
                _context = new Tren3Entities1();
            return _context;
        }

>>>>>>> Stashed changes:Model.Context.cs
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Sklad> Sklad { get; set; }
        public virtual DbSet<StroyMaterial> StroyMaterial { get; set; }
    }
}
